### ISSUE TITLE
BC01-01 註冊

### ISSUE THREAD

**Issue by zhao1995chen** [zhao1995chen/wowcho-api#1]
Middleware：註冊欄位驗證 & 檢查帳號與 E-mail 是否被使用

**Comment by chelly-hsu** [comment]
### API: /sign-up

### Request
account	string	帳號
password	string	密碼
email	string	信箱

### Response
{
	"code": 200,
	"message": "Success"
}

### 錯誤情況
- account 不符合格式
- account 已被使用
- email 已被使用
- email 不符合格式
- password 不符合格式


### SCHEMA 
  users 會員資料
		account	string	帳號	true	
		password	string	密碼	true	
		name	string	真實姓名	true	
		username	string	用戶名稱	true	
		email	string	信箱	true	



![Image](https://user-images.githubusercontent.com/111692708/233905621-b96c2f40-d3f7-4f03-86b7-eacd5f417c8d.jpg)

**Comment by zhao1995chen** [comment]
已合併至 dev
