### ISSUE TITLE
BC01-02 登入

### ISSUE THREAD

**Issue by zhao1995chen** [zhao1995chen/wowcho-api#2]
Middleware：登入欄位驗證

**Comment by chelly-hsu** [comment]
###API: /sign-up

###Request
account string 帳號
password string 密碼

###Response
{
	"code": 200,
	"message": "Success"
	"data": {
		"token": "xxxxxxx"
	}
}

###錯誤情況
    account 查無此帳號
    password 密碼錯誤

###SCHEMA users 會員資料
account string 帳號 true
password string 密碼 true

![Image](https://user-images.githubusercontent.com/111692708/233907169-ea365cf1-2cf5-4c04-98e1-c07ebe2f1ef9.jpg)

**Comment by zhao1995chen** [comment]
已合併至 dev
