### ISSUE TITLE
BC12-01 金流

### ISSUE THREAD

**Issue by guitimliu** [zhao1995chen/wowcho-api#23]
Middleware：贊助者金物流欄位驗證 & token

**Comment by chelly-hsu** [comment]
config.env新增
## Newebpay Payment ##
MerchantID=
HASHKEY=
HASHIV=
Version=
ReturnUrl=
NotifyURL=
PayGateWay=


1. 確認訂單
路由 money-flow/
view: money-flow.ejs
API GET: money-flow/
藍新MPG API串接: https://ccore.newebpay.com/MPG/mpg_gateway


2. 確認訂單 送金流API
API POST: money-flow/createOrder
DB collection建立Document:  moneyflows

3. 訂單交易成功客戶端顯示
路由: money-flow/newebpay-return
view: success.ejs
API POST: money-flow/newebpay-return
DB collection建立Document:  moneyflowsuccessorders

4. 幕後接收交易結果路由
API POST:  money-flow/newebpay-notify

**Comment by zhao1995chen** [comment]
@chelly-hsu 串接完成，後續交由 @rider159159 串接
