### ISSUE TITLE
BC01-07 修改密碼

### ISSUE THREAD

**Issue by guitimliu** [zhao1995chen/wowcho-api#63]
Middleware：贊助者修改密碼欄位驗證 & 舊密碼錯誤 & 舊密碼與新密碼相同、token

**Comment by chelly-hsu** [comment]
### Branch: feature/reset-password

### API: /reset-password

### Request
oldPassword string 舊密碼
newPassword string 新密碼

### Response
    {
    	"code": 200,
    	"message": "Success"
    }

### 錯誤情況
    oldPassword舊密碼錯誤 “您的舊密碼不正確”
    newPassword新密碼與舊密碼相同沒有變更 "新密碼不能與前次密碼相同"
    newPassword新密碼不符合格式 “密碼字數低於 8 碼”

    請填寫必填欄位

### SCHEMA users 會員資料
password string 密碼 true



![Image](https://user-images.githubusercontent.com/111692708/234088548-b8d48914-9670-4e80-8f86-9a3ad93b293a.png)
